class ApiRoutes {
  ApiRoutes._();

  /// V2 network contract. Feature services can keep their existing action
  /// identifiers during the migration; only this adapter knows GAS v1 names.
  static const Map<String, String> _legacyActionToV2Route = {
    'health': 'system.health',
    'app_update_info': 'system.appUpdateInfo',
    'home': 'dashboard.home',
    'analytics': 'analytics.monthly',
    'transactions': 'transactions.list',
    'ignored_transactions': 'transactions.ignored',
    'categories': 'categories.list',
    'budget_settings': 'budgets.settings',
    'import_history': 'imports.history',
    'master': 'master.bundle',
    'account_balances': 'accounts.balances',
    'balance_reconciliation': 'accounts.balanceReconciliation',
    'review_transactions': 'reviews.transactions',
    'review_count': 'reviews.count',
    'settlement_candidates': 'settlements.candidates',
    'settlement_statuses': 'settlements.statuses',
    'goals': 'goals.list',
    'gmail_import_status': 'gmail.importStatus',
    'recurring_candidates': 'recurring.candidates',
    'classification_rules': 'classification.rules',
    'merchant_classification_suggestions': 'classification.suggestions',
    'gmail_evidence_candidates': 'gmailEvidence.candidates',
    'investment_holdings': 'investments.holdings',
    'investment_price_history': 'investments.priceHistory',
    'investment_plans': 'investments.plans',
    'sbi_investment_events': 'investments.sbiEvents',
    'asset_trend': 'assets.trend',
    'business_report': 'business.report',
    'system_diagnostics': 'system.diagnostics',
    'r6_full_reconciliation': 'system.reconciliationAudit',
    'transaction_create': 'transactions.create',
    'transaction_update': 'transactions.update',
    'transaction_delete': 'transactions.delete',
    'transaction_manual_confirm': 'transactions.confirmPreliminary',
    'transaction_restore_ignored': 'transactions.restoreIgnored',
    'transaction_ignore': 'transactions.ignore',
    'csv_import': 'imports.csv',
    'csv_import_preview': 'imports.csvPreview',
    'discord_transaction': 'discord.transactions.create',
    'category_create': 'categories.create',
    'category_update': 'categories.update',
    'category_deactivate': 'categories.deactivate',
    'settlement_confirm': 'settlements.confirm',
    'settlement_manual_match': 'settlements.manualMatch',
    'settlement_manual_unmatch': 'settlements.manualUnmatch',
    'update_account_opening_balance': 'accounts.updateOpeningBalance',
    'balance_reconciliation_save': 'accounts.balanceReconciliation.save',
    'account_create': 'accounts.create',
    'account_update': 'accounts.update',
    'account_deactivate': 'accounts.deactivate',
    'budget_settings_update': 'budgets.settings.update',
    'goal_create': 'goals.create',
    'goal_update': 'goals.update',
    'goal_deactivate': 'goals.deactivate',
    'recurring_candidate_update': 'recurring.candidates.update',
    'classification_rule_create': 'classification.rules.create',
    'classification_rule_update': 'classification.rules.update',
    'classification_rule_delete': 'classification.rules.delete',
    'merchant_classification_suggestion_promote': 'classification.suggestions.promote',
    'gmail_evidence_scan': 'gmailEvidence.scan',
    'gmail_evidence_attach': 'gmailEvidence.attach',
    'gmail_evidence_ignore': 'gmailEvidence.ignore',
    'investment_holding_create': 'investments.holdings.create',
    'investment_holding_update': 'investments.holdings.update',
    'investment_holding_deactivate': 'investments.holdings.deactivate',
    'investment_prices_refresh': 'investments.prices.refresh',
    'investment_plan_save': 'investments.plans.save',
    'investment_plan_deactivate': 'investments.plans.deactivate',
    'sbi_investment_scan': 'investments.sbi.scan',
    'sbi_investment_event_apply': 'investments.sbi.apply',
    'sbi_investment_event_ignore': 'investments.sbi.ignore',
    'asset_snapshot_capture': 'assets.snapshot.capture',
    'business_tax_export_create': 'business.taxExport.create',
    'system_backup_create': 'system.backup.create',
    'system_integrity_check': 'system.integrity.check',
    'auth_status': 'auth.status',
    'auth_pair': 'auth.pair',
    'auth_revoke': 'auth.revoke',
    'backend_status': 'system.backendStatus',
  };

  static String fromLegacyAction(String action) {
    final normalized = action.trim();

    // Unknown values are passed through so tests/diagnostics can still exercise
    // error envelopes without teaching this adapter fake production routes.
    return _legacyActionToV2Route[normalized] ?? normalized;
  }
}
